language: php

sudo: true
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
  - php: nightly

before_script:
  - composer self-update
  - composer install --prefer-dist --dev

script: phpunit
